### ISSUE TITLE
Crashes on Android 5

### ISSUE THREAD

**Issue by kohenkatz** [yallie/drench#1]
Hello.

I hadn't tried to play this game since upgrading to Android 5 two months ago.  When I tried today, I had the following issue: the menu screen comes up properly, but then pressing any option on the menu closes the game and goes back to the home screen.

Device is Nexus 7 (2nd gen).

**Comment by yallie** [comment]
Thanks for reporting! That's a bug in Xamarin.Android used to compile the last version of the game. Sorry for this inconvenience.

**Comment by whamwham** [comment]
Hello! Is there any chance to solve this issue? I cannot switch to new phone because of your game not working. Device is yotaphone2, android 5... Anyway, thanks for your work!

**Comment by yallie** [comment]
Terribly sorry about that... I'm sure it can be solved, but I can't give any estimate. I'm afraid I can't afford to buy an Android5 device to experiment with the issue right now.

**Comment by yallie** [comment]
Fixed years ago, forgot to close the issue in time :)
